name: Triggers
run-name: Praxis 3 Triggers!
on:
  push:  #PUSH
    branches: ['main', 'aprendiendo-**']
    paths: ['**.yml']
  
  pull_request:  # PR
    types: [opened, labeled]
    branches: ['main', 'aprendiendo-**']
    paths: ['**.yml']
    
  schedule:  # SCHEDULE
    - cron: '59 23 * * SUN'
  
  workflow_dispatch:  # WORKFLOW_DISPATCH

jobs:
  job-t:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repo en el Runner
        uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
      
      - name: Define Variable IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Define Variable USERNAME   
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      
      - name: Run multi-line script
        run: |
          echo "Hello from IP: ${{ steps.ip.outputs.ipv4 }}"
          node main.js
